name: Deploy

on:
   workflow_dispatch:
   push:
      branches:
         - "main"

jobs:
  ssh_and_git_pull:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Connect to EC2 instance and Git Pull
        uses: appleboy/ssh-action@v1.0.0
        with:
         host: ec2-15-188-52-131.eu-west-3.compute.amazonaws.com
         username: ubuntu
         key: ${{ secrets.SSH_PUBLIC_KEY }}
         script: |
            cd /var/www/miranda_laravel
            ls
            git pull
            ls
